### ISSUE TITLE
JWT Expiration Handling Regression in Prisma SASE SDK v6.5.2b2 (elcapitan region)

### ISSUE THREAD

**Issue by hildebrau** [PaloAltoNetworks/prisma-sase-sdk-python#22]
Title: JWT Expiration Handling Regression in Prisma SASE SDK v6.5.2b2

Description:
The JWT expiration handling has regressed in Prisma SASE SDK v6.5.2b2, causing authentication failures with the error "API object has no attribute 'jwt_expires_at'". This issue was not present in the older CloudGenix SDK v6.3.1b1.

Environment:
- Working Environment:
  - CloudGenix SDK v6.3.1b1
  - cloudgenix_config v2.1.0b1
  - Python 3.9
  - Region: elcapitan

- Failing Environment:
  - Prisma SASE SDK v6.5.2b2
  - prisma_config v6.5.1b1
  - Python 3.9
  - Region: elcapitan

Steps to Reproduce:
1. Install Prisma SASE SDK v6.5.2b2
2. Install prisma_config v6.5.1b1
3. Attempt to use any SDK authentication method
4. Observe the error: "API object has no attribute 'jwt_expires_at'"

Expected Behavior:
The SDK should properly handle JWT expiration as it does in the older CloudGenix SDK v6.3.1b1.

Actual Behavior:
The SDK fails to initialize the jwt_expires_at attribute, causing authentication failures.

```(prisma-sase-sdk) [sdwan@USDC1-NEA1 sdwan_config]$ pull_site -S ALL_SITES -D 2 --multi-output /tmp
DEBUG [prisma_sase.get_api.sites:5466] URL = https://api.sase.paloaltonetworks.com/sdwan/v4.12/api/sites
Traceback (most recent call last):
  File "/home/sdwan/sdwan_config/prisma-sase-sdk/bin/pull_site", line 8, in <module>
    sys.exit(go())
  File "/home/sdwan/sdwan_config/prisma-sase-sdk/lib64/python3.9/site-packages/prisma_config/pull.py", line 2430, in go
    pull_config_sites(args['sites'], filename, output_multi=multi_output, normalize=normalize,
  File "/home/sdwan/sdwan_config/prisma-sase-sdk/lib64/python3.9/site-packages/prisma_config/pull.py", line 2153, in pull_config_sites
    update_global_cache()
  File "/home/sdwan/sdwan_config/prisma-sase-sdk/lib64/python3.9/site-packages/prisma_config/pull.py", line 345, in update_global_cache
    sites_resp = sdk.get.sites()
  File "/home/sdwan/sdwan_config/prisma-sase-sdk/lib64/python3.9/site-packages/prisma_sase/get_api.py", line 5467, in sites
    return self._parent_class.rest_call(url, "get")
  File "/home/sdwan/sdwan_config/prisma-sase-sdk/lib64/python3.9/site-packages/prisma_sase/__init__.py", line 1118, in rest_call
    if not self._refresh_jwt():
  File "/home/sdwan/sdwan_config/prisma-sase-sdk/lib64/python3.9/site-packages/prisma_sase/__init__.py", line 1868, in _refresh_jwt
    if self.jwt_expires_in <= 60:
  File "/home/sdwan/sdwan_config/prisma-sase-sdk/lib64/python3.9/site-packages/prisma_sase/__init__.py", line 1777, in jwt_expires_in
    return int(round((self.jwt_expires_at - datetime.datetime.now()).total_seconds()))
AttributeError: 'API' object has no attribute 'jwt_expires_at'
```

Error Details:
```python
AttributeError: 'API' object has no attribute 'jwt_expires_at'
```
The error occurs in the JWT refresh logic:
```python
if self.jwt_expires_in <= 60:
    return int(round((self.jwt_expires_at - datetime.datetime.now()).total_seconds()))
```

Analysis:
1. The issue appears to be a regression in the authentication flow
2. The older CloudGenix SDK v6.3.1b1 handles JWT expiration correctly
3. The issue persists across multiple versions of the Prisma SASE SDK
4. The error occurs during the authentication process, before any API calls are made
5. The issue is not related to package conflicts or dependencies

Impact:
- Unable to use the newer Prisma SASE SDK
- Forced to use older CloudGenix SDK for functionality
- Blocks migration to newer SDK features and improvements

Previous Related Issues:
- Similar issue reported in earlier versions of the SDK
- Issue appears to have resurfaced in v6.5.2b2

Additional Notes:
- Authentication works correctly in the older CloudGenix SDK v6.3.1b1
- The issue appears to be specific to the JWT expiration handling in the newer SDK
- Region-specific behavior may be relevant (testing in elcapitan region)

**Comment by hildebrau** [comment]
@sunkumarpanw , thanks for the response.  I used your example and it was successful at creating a list of sites for me w/o errors.  I then asked my AI agent to help pinpoint where the issue is and it came up with the following summary.  I'm happy to take it further if you have more questions.  We are a rather old tenant and who knows what cob webs we have in there that could be causing this.  However, if it wasn't clear on my earlier comment, the 'pull_site' command from prisma-config project is the one that was throwing the error.. but only when I use the newer SDK versions with it.

# JWT Expiration Handling Bug - Minimal Reproducible Example

## Summary

The `AttributeError: 'API' object has no attribute 'jwt_expires_at'` occurs when `_refresh_jwt()` is called before `jwt_expires_at` is initialized. This happens in `prisma_sase/__init__.py` at line 1869 when accessing `self.jwt_expires_in` property, which in turn tries to access `self.jwt_expires_at` (line 1778) without checking if it exists.

## Root Cause

**File:** `prisma_sase/__init__.py`

**Line 1869** (`_refresh_jwt` method):
```python
if self.jwt_expires_in <= 60:
```

**Line 1778** (`jwt_expires_in` property):
```python
return int(round((self.jwt_expires_at - datetime.datetime.now()).total_seconds()))
```

**Problem:** The code accesses `jwt_expires_in` property without first checking if `jwt_expires_at` attribute exists. This can occur in two scenarios:

1. **Failed `_generate_jwt()`**: If `_generate_jwt()` fails (returns `False`), `jwt_expires_at` is never set, but `rest_call()` may still call `_refresh_jwt()`.
2. **Edge case**: If `jwt_expires_at` is somehow cleared or never initialized, accessing the property raises `AttributeError`.

## Code Path

```
sdk.get.sites()
  └─> rest_call() [prisma_sase/__init__.py:1118]
      └─> if not self.use_jwt: _refresh_jwt()
          └─> _refresh_jwt() [line 1869: if self.jwt_expires_in <= 60:]
              └─> jwt_expires_in property [line 1778: self.jwt_expires_at]
                  └─> AttributeError: 'API' object has no attribute 'jwt_expires_at'
```

## Minimal Reproducible Example

Here's a Python script that reproduces the bug:

```python
#!/usr/bin/env python3
"""
Reproduces JWT expiration bug in Prisma SASE SDK v6.6.1b1
"""

from prisma_sase import API

# SCENARIO 1: jwt_expires_at missing (edge case)
print("SCENARIO 1: jwt_expires_at missing after successful login")
print("-" * 80)

sdk1 = API()
sdk1.client_id = 'your_client_id@tenant.iam.panserviceaccount.com'
sdk1.client_secret = 'your_client_secret'
sdk1.tsg_id = 1234567890

# Login successfully
sdk1.interactive.login_secret(
    client_id=sdk1.client_id,
    client_secret=sdk1.client_secret,
    tsg_id=sdk1.tsg_id
)

# Simulate jwt_expires_at being missing (this can happen in edge cases)
if hasattr(sdk1, 'jwt_expires_at'):
    delattr(sdk1, 'jwt_expires_at')
    print("✓ jwt_expires_at deleted to simulate bug condition")

# Now try to make an API call - this will trigger the bug
print("\nCalling sdk.get.sites() (triggers rest_call() -> _refresh_jwt())...")
try:
    response = sdk1.get.sites()
    print("✗ Unexpected: No error occurred")
except AttributeError as e:
    if 'jwt_expires_at' in str(e):
        print("✓ BUG REPRODUCED!")
        print(f"  Error: {e}")
        import traceback
        traceback.print_exc()

print("\n" + "=" * 80)
print("SCENARIO 2: _generate_jwt() fails, jwt_expires_at never set")
print("-" * 80)

# SCENARIO 2: _generate_jwt() fails
sdk2 = API()
sdk2.client_id = 'invalid_client_id'
sdk2.client_secret = 'invalid_secret'
sdk2.tsg_id = 1234567890
sdk2.grant_type = 'client_credentials'
sdk2.scope = f'tsg_id:{sdk2.tsg_id} email profile'

print("Attempting _generate_jwt() with invalid credentials...")
result = sdk2._generate_jwt()
print(f"  _generate_jwt() returned: {result}")
print(f"  - has jwt_expires_at: {hasattr(sdk2, 'jwt_expires_at')}")

if not hasattr(sdk2, 'jwt_expires_at'):
    print("  ✓ Confirmed: jwt_expires_at is NOT set after failed _generate_jwt()")
    print("\n  If rest_call() is called now, it will trigger the AttributeError")
```

## Actual Error Traceback

```
Traceback (most recent call last):
  File "/path/to/pull_site", line 8, in <module>
    sys.exit(go())
  File ".../prisma_config/pull.py", line 2430, in go
    pull_config_sites(args['sites'], filename, output_multi=multi_output, normalize=normalize,
  File ".../prisma_config/pull.py", line 2153, in pull_config_sites
    update_global_cache()
  File ".../prisma_config/pull.py", line 345, in update_global_cache
    sites_resp = sdk.get.sites()
  File ".../prisma_sase/get_api.py", line 5590, in sites
    return self._parent_class.rest_call(url, "get")
  File ".../prisma_sase/__init__.py", line 1118, in rest_call
    if not self._refresh_jwt():
  File ".../prisma_sase/__init__.py", line 1869, in _refresh_jwt
    if self.jwt_expires_in <= 60:
  File ".../prisma_sase/__init__.py", line 1778, in jwt_expires_in
    return int(round((self.jwt_expires_at - datetime.datetime.now()).total_seconds()))
AttributeError: 'API' object has no attribute 'jwt_expires_at'
```

## Suggested Fix

### Option 1: Check in `_refresh_jwt()` (Recommended)

Modify `prisma_sase/__init__.py` at line 1869:

**Current:**
```python
def _refresh_jwt(self):
    """
    refresh token method to regenerate token before it expires.
    """
    if self.jwt_expires_in <= 60:
```

**Fixed:**
```python
def _refresh_jwt(self):
    """
    refresh token method to regenerate token before it expires.
    """
    if not hasattr(self, 'jwt_expires_at') or self.jwt_expires_in <= 60:
```

### Option 2: Handle in `jwt_expires_in` Property

Modify `prisma_sase/__init__.py` at line 1773:

**Current:**
```python
@property
def jwt_expires_in(self):
    """
    :returns expires_in
    """
    return int(round((self.jwt_expires_at - datetime.datetime.now()).total_seconds()))
```

**Fixed:**
```python
@property
def jwt_expires_in(self):
    """
    :returns expires_in
    """
    if not hasattr(self, 'jwt_expires_at'):
        return 0  # Return 0 to trigger refresh if jwt_expires_at doesn't exist
    return int(round((self.jwt_expires_at - datetime.datetime.now()).total_seconds()))
```

## Recommendation

I recommend **Option 1** as it's more explicit and handles the edge case at the point where it's checked. Option 2 would also work but might mask other issues.

## Testing

The bug was reproduced using:
- **SDK Version**: 6.6.1b1 (from `release/6.6.1.b1` branch)
- **Python Version**: 3.9
- **Environment**: Prisma SASE elcapitan region
- **prisma_config version**: 6.5.1b2

The issue also affects versions 6.5.2b2 and 6.4.2b1 as mentioned in the original issue.

## Additional Context

The bug manifests when using `prisma_config`'s `pull_site` command, which:
1. Creates SDK instance: `sdk = prisma_sase.API()`
2. Calls `sdk.interactive.login_secret()` 
3. Immediately calls `sdk.get.sites()` in `update_global_cache()`

This sequence can trigger `_refresh_jwt()` before `jwt_expires_at` is properly initialized in some edge cases.

**Comment by hildebrau** [comment]
My AI agent wants to apologize.. ;). The variable naming convention evolution caused this nightmare.. but I'm onboard now w/ the new names (minus another underscore).. so, I think we're good for now.  Mr. Agent does suggest one minor change in the SDK.. I am not as convinced, though.


# Follow-up: Root Cause Analysis and Minimal Fix

## Apology and Clarification

First, I apologize for the confusion in my original report. After further investigation, I discovered that the immediate issue was actually a **settings file configuration problem**, not just the SDK bug. However, the SDK bug **does exist** and manifests in edge cases and error scenarios.

## Settings File Issue

The root cause of my immediate problem was that `prisma_config` expects:
- **File name:** `prismasase_settings.py` (no underscore between "prisma" and "sase")
- **Variable names:** `PRISMASASE_CLIENT_ID`, `PRISMASASE_CLIENT_SECRET`, `PRISMASASE_TSG_ID`

I had `prisma_sase_settings.py` (with underscore) with `PRISMA_SASE_*` variables, which caused credentials to not load, so `login_secret()` was never called. This triggered the SDK bug because `rest_call()` → `_refresh_jwt()` was called on an unauthenticated SDK instance.

After fixing the settings file, `pull_site` works in normal operation. However, the SDK bug still exists and would manifest in these scenarios:
- Login failures (bad credentials, network issues)
- SDK used before login
- Token regeneration failures
- Any code path where `rest_call()` is called before `jwt_expires_at` is initialized

## Variable Name Progression

The variable naming has evolved over time, which explains the confusion:

```
Historical progression:
- Cloudgenix era: CLOUDGENIX_* variables
- Prisma SD-WAN transition: PRISMASDWAN_* variables  
- Prisma SASE (current): PRISMASASE_* variables (no underscore)
- Also seen: PRISMA_SASE_* (with underscore) - this is what I had
```

The current `prisma_config 6.5.1b2` expects `PRISMASASE_*` (no underscore), which matches the file name `prismasase_settings.py`.

## Minimal Fix Required

The minimal fix is a **one-line change** in `prisma_sase/__init__.py` at line 1869-1870:

**Before (BUG):**
```python
def _refresh_jwt(self):
    """
    refresh token method to regenerate token before it expires.
    """
    if self.jwt_expires_in <= 60:  # ❌ Crashes if jwt_expires_at doesn't exist
```

**After (FIXED):**
```python
def _refresh_jwt(self):
    """
    refresh token method to regenerate token before it expires.
    """
    # Check if jwt_expires_at exists before accessing jwt_expires_in property
    if not hasattr(self, 'jwt_expires_at') or self.jwt_expires_in <= 60:  # ✅ Safe
```

## Why This Fix Matters

Even though `pull_site` works after fixing the settings file, this defensive fix is important because:

1. **Robustness**: Prevents crashes in error scenarios (failed login, network issues, etc.)
2. **Edge Cases**: Handles cases where SDK is used without proper authentication
3. **Token Regeneration**: Protects against failures during token refresh
4. **Developer Experience**: Provides clearer error handling instead of cryptic `AttributeError`

## Testing

After applying the minimal fix:
- ✅ `pull_site` works in normal operation (with proper settings file)
- ✅ SDK handles missing `jwt_expires_at` gracefully (returns `False` instead of crashing)
- ✅ Bug reproduction test passes (deleting `jwt_expires_at` no longer crashes)

## Recommendation

The minimal fix should be applied to make the SDK more robust. The settings file issue was a configuration problem on my end, but the SDK bug is real and should be fixed to handle edge cases properly.

Thank you for your patience, and apologies for the initial confusion!
